"""icecreamML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zuF7rMHEra1CiLI9qjLhWS9V2g22bsv

# Importing Libaries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IceCreamData.csv')

df.head()

df.tail()

df.shape

df.info()

df.isnull().sum()

df.describe()

df.columns

plt.scatter(df.Temperature, df.Revenue)
plt.xlabel('Temperature')
plt.ylabel('Revenue')

sns.heatmap(df.corr(), annot=True, cmap='Greens')

model = LinearRegression()

X = df.Temperature.values.reshape(-1,1)
y = df.Revenue

df.ndim

df.Temperature.ndim

df.Temperature.values.reshape(-1,1).ndim

X

y

X.ndim

y.ndim

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

len(X_train)

len(X_test)

len(y_train)

len(y_test)

model.fit(X_train, y_train)

#y = mx + c

model.intercept_

model.coef_

y_pred = model.predict(X_test)

r2_score(y_test, y_pred)

model.predict([[30]])

with open('model.pkl','wb') as files:
    pickle.dump(model,files)
